matfile: 'kiddo.mat'
verbose_level: 1
crop:
  left_top:
    x: 679
    y: 871
  size:
    width: 600
    height: 600
layers:
  - 1
input_dimensions:
  min: 27
  max: 27 # maximum is included into selection
output_dimensions:
  min: 27
  max: 27
expected_max_px_misplacement: 15
inside_part: 150
outside_part: 15
layer_normalization:
  shift: 2000
  scale: 0.1
  rotation: 0.1
  radial_distortion: 0.01
  radial_distortion_2: 0.01
  radial_distortion_3: 0.005
train:
  batch_size: 2048
  stages:
    - type: adam_rd
      epochs: 500
    - type: sgd_rd
      epochs: 500
  use_gpu: false
  shift_learning_multi: 10 # to achieve different learning rate for shift and rotation
  shift_learning_multi_2: 700000
  optimizer:
    family: "adam"
    learning_rate: 0.00025
    beta1: 0.9
    beta2: 0.999
  refiner:
    family: "SGD"
    learning_rate: 3.0
    decay: 0.01
    momentum: 0.99

