matfile: 'C:/Pycharm_projects/igre/input/vlasic.mat'
crop:
  left_top:
    x: 0
    y: 0
  size:
    width: 401
    height: 401
layers:
  - 1
input_dimensions:
  min: 27
  max: 27 # maximum is included into selection
output_dimensions:
  min: 27
  max: 27
expected_max_shift_px: 20
train:
  batch_size: 2048
  epochs: 150
  use_gpu: false
  optimizer:
    family: "adam"
    learning_rate: 0.35
    beta1: 0.01
    beta2: 0.85