matfile: '../../input/vlasic-dataset.mat'
verbose_level: 0
crop:
  left_top:
    x: 0
    y: 0
  size:
    width: 300
    height: 400
layers:
  - 1
input_dimensions:
  min: 27
  max: 27 # maximum is included into selection
output_dimensions:
  min: 27
  max: 27
expected_max_px_misplacement: 25
stages:
  - type: blur
    params: 51
    epochs: 75
  - type: blur
    params: 21
    epochs: 75
refine_epochs: 100
train:
  batch_size: 2048
  epochs: 100
  use_gpu: false
  shift_learning_multi: 10 # to achieve different learning rate for shift and rotation
  shift_learning_multi_2: 700000
  optimizer:
    family: "adam"
    learning_rate: 0.7
    beta1: 0.9
    beta2: 0.8
  refiner:
    family: "SGD"
    learning_rate: 1.1
    decay: 0.001
    momentum: 0.99