matfile: 'vlasic-dataset.mat'
verbose_level: 1
crop:
  left_top:
    x: 0
    y: 0
  size:
    width: 300
    height: 400
layers:
  - 1
input_dimensions:
  min: 25
  max: 25 # maximum is included into selection
output_dimensions:
  min: 27
  max: 27
expected_max_px_misplacement: 25
train:
  batch_size: 2048
  stages:
    - type: blur
      params: 101
      epochs: 50
      extrapolation_layers_trainable : False # default True
      #registration_layers_trainable : False # default True
    - type: blur
      params: 51
      epochs: 20
      extrapolation_layers_trainable : False # default True
      #registration_layers_trainable : False # default True
    - type: polish
      epochs: 100
      extrapolation_layers_trainable : False # default True
      #registration_layers_trainable : False # default True
    - type: refine
      epochs: 50
      #extrapolation_layers_trainable : False # default True
      #registration_layers_trainable : False # default True
  use_gpu: false
  shift_learning_multi: 700 # to achieve different learning rate for shift and rotation
  shift_learning_multi_2: 700000
  optimizer:
    family: "adam"
    learning_rate: 0.75
    beta1: 0.85
    beta2: 0.999
  refiner:
    family: "SGD"
    learning_rate: 1.1
    decay: 0.001
    momentum: 0.99
